In [1]:
#Import dask
import dask.dataframe as dd

In [10]:
#Specify metatype to faster analysis
types = {'camino': str, 'organismo_nombre': str, 'organismo_codigo': str, 'fecha_publicacion': str,
       'anyo': str, 'Mes': str, 'nombre': str, 'Tipo cargo': str, 'grado_eus': str,
       'tipo_calificacionp': str, 'region': str, 'asignaciones': str, 'Tipo Unidad monetaria': str,
       'remuneracionbruta_mensual': float, 'remuliquida_mensual': float, 'diurnas': str,
       'nocturnas': str, 'fecha_ingreso': str, 'fecha_termino': str, 'observaciones': str,
       'viaticos': str, 'enlace': str}


types2 = {'camino' : str,
'organismo_nombre' : str,
'organismo_codigo' : str,
'fecha_publicacion' : str,
'anyo' : str,
'Mes' : str,
'Tipo' : str,
'Estamento' : str,
'Nombres' : str,
'Paterno' : str,
'Materno' : str,
'grado_eus' : str,
'tipo_calificacionp' : str,
'Tipo cargo' : str,
'region' : str,
'asignaciones' : str,
'Tipo Unidad monetaria' : str,
'remuneracionbruta_mensual' : float,
'remuliquida_mensual' : float,
'Pago extra diurnas' : str,
'Horas extra diurnas' : str,
'Pago extra nocturnas' : str,
'Horas extra nocturnas' : str,
'Pago extra festivas' : str,
'Horas extra festivas' : str,
'fecha_ingreso' : str,
'fecha_termino' : str,
'observaciones' : str,
'enlace' : str,
'viaticos' : str}

path_codigotrabajo = 'data publica/PersonalCodigotrabajo.csv'
path_contrata = 'data publica/PersonalContrata.csv'
path_contratohonorarios = 'data publica/PersonalContratohonorarios.csv'
path_planta = 'data publica/PersonalPlanta.csv'

#Read
df_codigotrabajo = dd.read_csv(path_codigotrabajo, encoding='ISO-8859-1', delimiter=';', dtype = types)
df_contrata = dd.read_csv(path_contrata, encoding='ISO-8859-1', delimiter=';', dtype = types2)
df_honorarios = dd.read_csv(path_contratohonorarios, encoding='ISO-8859-1', delimiter=';', dtype = types)
df_planta = dd.read_csv(path_planta, encoding='ISO-8859-1', delimiter=';', dtype = types)

In [41]:
df_codigotrabajo.head()

,camino,organismo_nombre,organismo_codigo,fecha_publicacion,anyo,Mes,Nombres,Paterno,Materno,Tipo cargo,...,Pago extra nocturnas,Horas extra nocturnas,Pago extra festivas,Horas extra festivas,fecha_ingreso,fecha_termino,observaciones,viaticos,enlace,activado
0,/Año 2017/Enero,Municipalidad de Vicuña,MU335,2017/03/09,2017,Enero,César,Puebla,Ruíz,Analista,...,NaN,NaN,NaN,NaN,01/01/2017,31/12/2017,Sin observaciones,NaN,No,SÍ
1,/Año 2017/Enero,Municipalidad de Vicuña,MU335,2017/03/09,2017,Enero,Nicolás,Puebla,Gallardo,RELATOR,...,NaN,NaN,NaN,NaN,01/01/2017,01/12/2017,Sin observaciones,NaN,a href=http:www.google.com target=_blankwww.go...,SÍ
2,/Año 2018/Abril,Asociación de Municipalidades Territorio de Ri...,MA011,2021/08/11,2018,Abril,Gina Maria,Hidalgo,Cancino,Secretaria Ejecutiva,...,NaN,NaN,NaN,NaN,16/04/2018,Indefinido,Sin observaciones,NaN,No,SÍ
3,/2018/Febrero,Ex Consejo Nacional de la Cultura y las Artes ...,AV001,2018/05/15,2018,Enero,ELIZABETH DEL CARMEN,GONZALEZ,ANATIVIA,JEFA VESTUARIO,...,NaN,NaN,NaN,NaN,01/01/2006,Indefinido,Sin observaciones,NaN,No,SÍ
4,/2018/Febrero,Ex Consejo Nacional de la Cultura y las Artes ...,AV001,2018/05/15,2018,Enero,CLAUDIO,GONZALEZ,MALDONADO,SUB DIRECTOR MUSICAL,...,NaN,NaN,NaN,NaN,01/01/2006,Indefinido,Sin observaciones,NaN,No,SÍ

In [39]:
df_contrata.head()

,camino,organismo_nombre,organismo_codigo,fecha_publicacion,anyo,Mes,Tipo Estamento,Nombres,Paterno,Materno,...,Pago extra nocturnas,Horas extra nocturnas,Pago extra festivas,Horas extra festivas,fecha_ingreso,fecha_termino,observaciones,enlace,viaticos,activado
0,/Pagina 3,Partido Ciudadanos,PP030,2016/06/29,2016,Mayo,Administrativo,CRISTIAN ESTEBAN,AVILEZ,STUARDO,...,NaN,NaN,NaN,NaN,08/03/2010,07/01/2014,Esto es un funcionario de prueba,No,NaN,SÍ
1,/Pagina 3,Partido Ciudadanos,PP030,2016/06/29,2016,Marzo,Profesional,IVAN ANDRES,SALINAS,BALAGNA,...,NaN,NaN,NaN,NaN,25/09/2010,27/07/2014,Esto es un funcionario de prueba,No,NaN,SÍ
2,/Pagina 3,Partido Ciudadanos,PP030,2016/06/29,2016,Marzo,Auxiliar,SERGIO ANTONIO,SAAVEDRA,VILCHES,...,NaN,NaN,NaN,NaN,24/09/2010,26/07/2014,Esto es un funcionario de prueba,No,NaN,SÍ
3,/Pagina 3,Partido Ciudadanos,PP030,2016/06/29,2016,Marzo,Profesional,TAMARA ISABEL,RUBIO,THAMM,...,NaN,NaN,NaN,NaN,23/09/2010,25/07/2014,Esto es un funcionario de prueba,No,NaN,SÍ
4,/Pagina 3,Partido Ciudadanos,PP030,2016/06/29,2016,Marzo,Auxiliar,KARYN LORENA,REYES,VIDAL,...,NaN,NaN,NaN,NaN,22/09/2010,24/07/2014,Esto es un funcionario de prueba,No,NaN,SÍ

In [38]:
df_honorarios.head()

,camino,organismo_nombre,organismo_codigo,fecha_publicacion,anyo,Mes,Nombres,Paterno,Materno,grado_eus,...,Tipo Unidad monetaria,remuneracionbruta,remuliquida_mensual,pago_mensuales,fecha_ingreso,fecha_termino,observaciones,enlace,viaticos,activado
0,/Año 2017/Mayo,Asociación de Municipalidades del Valle del Maipo,MA049,2021/09/04,2017,Junio,Luis,Céspedes,Inostroza,No asimilado a Grado,...,Pesos,888889,800000.0,Sí,2016/06/01 00:00:00.000,31/12/2017,Sin observaciones,No,NaN,SÍ
1,/Año 2017/Junio,Asociación de Municipalidades del Valle del Maipo,MA049,2021/09/04,2017,Junio,Luis,Céspedes,Inostroza,No asimilado a Grado,...,Pesos,888889,800000.0,Sí,2016/06/01 00:00:00.000,31/12/2017,Sin observaciones,No,NaN,SÍ
2,/Año 2017/Julio,Asociación de Municipalidades del Valle del Maipo,MA049,2021/09/04,2017,Junio,Luis,Céspedes,Inostroza,No asimilado a Grado,...,Pesos,888889,800000.0,Sí,2016/06/01 00:00:00.000,31/12/2017,Sin observaciones,No,NaN,SÍ
3,/Año 2017/Agosto,Asociación de Municipalidades del Valle del Maipo,MA049,2021/09/04,2017,Junio,Luis,Céspedes,Inostroza,No asimilado a Grado,...,Pesos,888889,800000.0,Sí,2016/06/01 00:00:00.000,31/12/2017,Sin observaciones,No,NaN,SÍ
4,/2017/Noviembre,Asociación Municipalidades Provincia de Llanqu...,MA025,2017/12/21,2017,Noviembre,Alejandro Javier,Bórquez,Felmer,No asimilado a grado,...,Pesos,1700000,1530000.0,Sí,2016/12/01 00:00:00.000,31/12/2017,Sin observaciones,No,NaN,SÍ

In [37]:
df_planta.head()

,camino,organismo_nombre,organismo_codigo,fecha_publicacion,anyo,Mes,Tipo Estamento,Nombres,Paterno,Materno,...,Pago extra nocturnas,Horas extra nocturnas,Pago extra festivas,Horas extra festivas,fecha_ingreso,fecha_termino,observaciones,enlace,viaticos,activado
0,/Municipal/Municipal Año 2014/Septiembre,Municipalidad de Puchuncaví,MU229,2015/02/27,2014,Julio,Administrativo,PAOLA ANDREA,ARANGUIZ,PEZO,...,NaN,NaN,NaN,NaN,02/11/2011,Indefinido,SIN OBSERVACIONES,No,0.0,SÍ
1,/Municipal/Municipal Año 2014/Septiembre,Municipalidad de Puchuncaví,MU229,2015/02/27,2014,Julio,Auxiliar,GERMAN ANDRES,QUINTANILLA,QUINTANILLA,...,NaN,NaN,NaN,NaN,19/12/1992,Indefinido,SIN OBSERVACIONES,No,0.0,SÍ
2,/Municipal/Municipal Año 2014/Septiembre,Municipalidad de Puchuncaví,MU229,2015/02/27,2014,Julio,Técnico,ROSA MARIA,QUILPATAY,LASTRA,...,NaN,NaN,NaN,NaN,03/01/1994,Indefinido,SIN OBSERVACIONES,No,0.0,SÍ
3,/Municipal/Municipal Año 2014/Septiembre,Municipalidad de Puchuncaví,MU229,2015/02/27,2014,Julio,Administrativo,MIGUEL FRANCISCO,QUILPATAY,LASTRA,...,NaN,NaN,NaN,NaN,01/08/2011,Indefinido,SIN OBSERVACIONES,No,0.0,SÍ
4,/Municipal/Municipal Año 2014/Septiembre,Municipalidad de Puchuncaví,MU229,2015/02/27,2014,Julio,Técnico,EULALIA ELENA,QUILODRAN,P0BLETE,...,NaN,NaN,NaN,NaN,17/12/1984,Indefinido,SIN OBSERVACIONES,No,0.0,SÍ

In [50]:
dfs = {df_codigotrabajo : 'Codigotrabajo',
        df_contrata : 'Contrata',
        df_honorarios : 'Honorarios',
        df_planta : 'Planta'}

Anyo = 2020

Meses = {'Abril',
         'Agosto',
         'Diciembre',
         'Enero',
         'Febrero',
         'Julio',
         'Junio',
         'Marzo',
         'Mayo',
         'Noviembre',
         'Octubre',
         'Septiembre'}


aux = {}

for df in dfs:
    
    currentYear = df[df.anyo == str(Anyo)]
    mes = 'Febrero'
    month =  currentYear[currentYear.Mes == mes]
    aux[dfs[df]] = month
    month.to_csv('data publica/por contrato/' + mes + str(Anyo) + dfs[df] +'.csv', single_file = True)

    #for mes in Meses:
    #    month =  currentYear[currentYear.Mes == mes]
    #    month.to_csv('data publica/por mes/' + mes + str(Anyo) + dfs[df] +'.csv', single_file = True)

In [52]:
target = 0
for a in aux:
    lenght = len(aux[a].index)
    print(a + ' : ' + str(lenght))
    target += lenght
print('lenght: ', target)

Codigotrabajo : 111184
Contrata : 310300
Honorarios : 91390
Planta : 162111
lenght:  674985

In [53]:
df_whole = dd.concat(list(aux.values()))
len(df_whole.index)

674985

In [54]:
df_whole.to_csv('data publica/unidos/' + mes + str(Anyo) + '.csv', single_file = True)

['/Users/nicolasvega/Desktop/Personal/transparency-project/paper/data publica/unidos/Febrero2020.csv']